// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol KeysGlobalProtocol {
    var marvelPublicKey: String { get }
    var marvelPrivateKey: String { get }
}

public protocol KeysEnvironmentProtocol {
}
